-- ============================================================================
-- H2 Database Schema for MediaVerwaltung
-- ============================================================================
-- Version: 1.0
-- Date: 2025-10-10
-- Database: H2 2.x
-- ============================================================================

-- Drop table if exists (for clean re-creation)
DROP TABLE IF EXISTS MEDIA_ITEM;

-- ============================================================================
-- Table: MEDIA_ITEM
-- ============================================================================
-- Stores all media items (videos, audio, text articles)
-- ============================================================================

CREATE TABLE MEDIA_ITEM (
    -- Primary Key (auto-increment)
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    
    -- Timestamp (auto-set on INSERT, updated via JPA @PreUpdate)
    LAST_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Required: URL to the media source
    URL CHARACTER VARYING(1000) NOT NULL,
    
    -- Optional: Description/Title
    BESCHREIBUNG CHARACTER VARYING(1000),
    
    -- Optional: Channel/Creator name
    CHANNEL CHARACTER VARYING(255),
    
    -- Optional: Duration (format: HH:MM:SS or MM:SS)
    DAUER CHARACTER VARYING(255),
    
    -- Optional: Keywords/Tags (comma-separated for now)
    STICHWORT CHARACTER VARYING(255),
    
    -- Optional: Media type (VIDEO, AUDIO, TEXT)
    MEDIA_TYPE CHARACTER VARYING(255),
    
    -- Constraints
    CONSTRAINT PK_MEDIA_ITEM PRIMARY KEY (ID)
);

-- ============================================================================
-- Indexes (optional, for performance)
-- ============================================================================

-- Index on MEDIA_TYPE for fast filtering
CREATE INDEX IF NOT EXISTS IDX_MEDIA_TYPE ON MEDIA_ITEM(MEDIA_TYPE);

-- Index on CHANNEL for fast filtering
CREATE INDEX IF NOT EXISTS IDX_CHANNEL ON MEDIA_ITEM(CHANNEL);

-- ============================================================================
-- Comments (H2 supports column comments)
-- ============================================================================

COMMENT ON TABLE MEDIA_ITEM IS 'Stores all media items (videos, audio, text)';
COMMENT ON COLUMN MEDIA_ITEM.ID IS 'Primary key, auto-increment';
COMMENT ON COLUMN MEDIA_ITEM.LAST_UPDATED_AT IS 'Last modification timestamp';
COMMENT ON COLUMN MEDIA_ITEM.URL IS 'Source URL (required field)';
COMMENT ON COLUMN MEDIA_ITEM.BESCHREIBUNG IS 'Description or title';
COMMENT ON COLUMN MEDIA_ITEM.CHANNEL IS 'Channel or creator name';
COMMENT ON COLUMN MEDIA_ITEM.DAUER IS 'Duration (e.g. 00:15:30)';
COMMENT ON COLUMN MEDIA_ITEM.STICHWORT IS 'Keywords/Tags';
COMMENT ON COLUMN MEDIA_ITEM.MEDIA_TYPE IS 'Type: VIDEO, AUDIO, TEXT';

-- ============================================================================
-- Sample Data (optional, for testing)
-- ============================================================================

INSERT INTO MEDIA_ITEM (URL, BESCHREIBUNG, CHANNEL, DAUER, STICHWORT, MEDIA_TYPE) VALUES
('https://youtube.com/watch?v=dQw4w9WgXcQ', 'Never Gonna Give You Up', 'Rick Astley', '00:03:33', 'music,80s', 'VIDEO'),
('https://youtube.com/watch?v=9bZkp7q19f0', 'Gangnam Style', 'PSY', '00:04:13', 'kpop,viral', 'VIDEO'),
('https://spotify.com/episode/example', 'Tech Talk Episode 1', 'TechPodcast', '00:45:00', 'tech,podcast', 'AUDIO'),
('https://medium.com/@user/ai-article', 'Understanding AI in 2025', 'AI Weekly', NULL, 'ai,tech', 'TEXT');

-- ============================================================================
-- End of Schema
-- ============================================================================
